/////////////////////
// make pitches
////////////////////

{|parent|

  parent.sound.stage1.pitches = [189/128, 7/4, 49/32, 1/1, 21/16];
  parent.sound.stage2.pitches = [189/128, 441/256, 7/6, 3/2, 49/32];
  parent.sound.stage3.pitches = [7/6, 189/128, 21/16, 4/3, 49/48];
  parent.sound.stage4.pitches = [1/1, 7/6, 189/128, 3/2, 4/3];
  parent.sound.stageREM.pitches = [189/128, 3/2, 1/1, 7/4, 63/32];

}
